server:
  port: 80
  ssl:
    enabled: false
spring:
  thymeleaf:
    mode: HTML
    cache: false
  datasource:
      url: jdbc:mysql://localhost:3306/factory?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=true
      username: factory
      password: factory
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
logging:
  level:
    com.keveon: trace
    org.hibernate: warn
    org.springframework: warn